# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df4bf40885d747e0f2fdea33bc5039f282760151c06c3ee5e7039dd985e7f388d1494f373d50f8a06793e5cf1ccca6e696d4cd41bf6c6ae272049155fe1a00ba

test:
  secret_key_base: 96bdb984bd5d955a3f6a3aeaa7b306f68185ad9681d7fbc9433b39695afda07c98cb6db25bba8d3f8d8f10a64d38373b9d5d17a606d6f5f360f880c7022580a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
